config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: 'info_window', locals: { flat: flat }),
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save!
    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.label :name, required: true%>
  <%= f.text_field :name,  required: true %>
  <%= f.label :address, required: true %>
  <%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.label :description, required: true %>
  <%= f.text_field :description, required: true %>
  <%= f.label :price_per_night, required: true %>
  <%= f.number_field :price_per_night, required: true %>
  <%= f.label :number_of_guests, required: true %>
  <%= f.number_field :number_of_guests, required: true %>

  <%= f.input :picture_url, as: :file  %>
  <%= f.submit %>

<% end %>

app/views/flats/_info_window.html.erb
<h1><%= flat.name %></h1>
<h2><%= flat.address %></h2>
<p><%= flat.description %></p>
<p><%= flat.price_per_night %></p>
<p><%= flat.number_of_guests %></p>

app/views/flats/edit.html.erb
<h1 class="text-center">Edit your Flat</h1>

<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="text-center justify-content-center align-items-center">
  <h1>All our flats</h1>

  <p class=" align-items-end"><%= link_to "add new flat", new_flat_path %></p>




  <div class="row w-400 m-auto">
    <% @flats.each do |flat| %>
      <div class="col-sm-4 my-3">
        <div class="card">
          <div class="card-body">
            <img src="<%#= cl_image_tag flat.photo.key, height: 300, width: 400, crop: :fill %>" alt="">
            <h2 class="card-title"><%= flat.name %></h2>
            <h4 class="card-text"><%= flat.address %></h4>
            <p class="card-text"><%= flat.description %></p>
            <div class="infos">
              <i class="fa-solid fa-user-group mx-2"> <%= flat.number_of_guests %></i>
              <i class="fa-solid fa-euro-sign"> <%= flat.price_per_night %></i>
            </div>
            <%= link_to "more info", flat_path(flat) %>
          </div>
        </div>
      </div>
      <% end %>
  </div>

  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/flats/new.html.erb
<h1 class="text-center my-4">create your Flat</h1>

<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<h1>Your Flat</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Description</th>
      <th scope="col">price_per_night</th>
      <th scope="col">number_of_guests</th>
      <th>edit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @flat.name %></th>
      <td><%= @flat.address %></td>
      <td><%= @flat.description %></td>
      <td><%= @flat.price_per_night %></td>
      <td><%= @flat.number_of_guests %></td>
      <td><%= link_to "edit", edit_flat_path(@flat) %></td>
    </tr>
  </tbody>

</table>
  <%= link_to "back to list", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="../assets/stylesheets/css/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>